import { Roboto_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const roboto_Mono = Roboto_Mono({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header id="page-heading" className="font-bold text-2xl">
          A History of Culture
        </header>
        <nav className="my-3">
          <ul className="flex flex-row gap-10 justify-center">
            <li>
              <Link href="/">Home</Link>
            </li>
            <li>
              <Link href="/blog">Blog</Link>
            </li>
            <li>
              <Link href="/about">About</Link>
            </li>
          </ul>
        </nav>
        <main>{children}</main>
        <footer>
          This site is heavily influenced by the works of{" "}
          <Link href="https://www.youtube.com/@underthefigtreee">
            @underthefigtree
          </Link>
        </footer>
      </body>
    </html>
  );
}
